spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jayczx120
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bonc.springboot_springsecurity_thymeleaf.pojo
